### ISSUE TITLE
Final changes for the 3.0 release

### ISSUE THREAD

**Issue by giovannipizzi** [wannier-developers/wannier90#229]
Tasks for preparing the release
- [x] Make sure the new version number is written everywhere (Makefile, User guide, tutorial,  README, and there is a string in `io.F90`
- [x] Fix readme of examples of tutorial (~3 examples are missing)
- [x] Decide if we want to avoid putting the compiled PDFs on git and instead e.g. using travis+github pages for them [probably for this release we keep as it is now]
- [x] Add arXiv reference of paper [moved after release in #240]
- [x] If needed update the date of the release (code header, User guide, tutorial, README, ...) - think also if we need to keep the date in so many places
- [x] Double check that the pw2wannier90.f90 file did not change in the main repository of Quantum ESPRESSO (see #231)
- [x] Update the CHANGELOG with the few remaining commits after (and including some of) Jan 18th
- [x] Fix release date in docs, parameters.F90, ...
- [x] Check if it is safe to rename post_6.3 to 6.4 (or if we should do it right after the release: make an issue, then)
- [x] Fix `make dist` to use `git archive`
- [x] Check if the copyright lines are all updated if they refer to the year
- [x] Update the PDF of tutorial, user_guide and solutions
- [x] Update the FORD documentation [moved to #114]
- [x] Update the website
- [x] Tag the release, possibly releasing a version of the .tar.gz released with the Makefile to be a bit slimmer
- [x] Fix `make dist` to use the git tag
- [x] Prepare compiled docs (3 PDF), and FORD documentation
- [x] Make sure the new QE will link to the new release
