### ISSUE TITLE
Update pw2wannier90 to QE

### ISSUE THREAD

**Issue by giovannipizzi** [wannier-developers/wannier90#231]
## Task
We need to sync the pw2wannier90.f90 file to the new changes in QE.
Here, I'll refer at QE 6.4 to the next release of QE, scheduled for Feb 28 2019 (see [gitlab](https://www.gitlab.com/QEF/q-e))

You can check the three versions here:
- [pw2wannier90.f90 from QE tag qe-6.3](https://github.com/wannier-developers/wannier90/files/2786033/pw2wannier90-qe-6.3.f90.txt)
- [pw2wannier90.f90 from QE branch develop on 23 Jan 2019](https://github.com/wannier-developers/wannier90/files/2786034/pw2wannier90-qe-develop-20190123-almost640.f90.txt)
- [pw2wannier90 inside our Wannier90 repo, folder `post_v6.2.1` (to be probably renamed v6.3)](https://github.com/wannier-developers/wannier90/files/2786036/pw2wannier90-w90-post621.f90.txt)

## Suggested action
- [ ] rename the folder `post_v6.2.1` to `v6.3`
- [ ] create a folder `post_v6.3`, sync the file with the minimal changes to the modules names in QE
- [ ] make a merge request to the QE repo with these latter changes

## Details on diff here below
In particular:
- Between QE 6.3 and QE 6.4, the only change in QE has been the renaming of `wavefunctions_module` to `wavefunctions`:

```diff
--- pw2wannier90-qe-6.3.f90.txt	2019-01-23 07:38:53.000000000 +0100
+++ pw2wannier90-qe-develop-20190123-almost640.f90.txt	2019-01-23 07:37:06.000000000 +0100
@@ -1223,7 +1223,7 @@
    USE kinds,           ONLY: DP
    USE wvfct,           ONLY : nbnd, npwx
    USE control_flags,   ONLY : gamma_only
-   USE wavefunctions_module, ONLY : evc, psic, psic_nc
+   USE wavefunctions, ONLY : evc, psic, psic_nc
    USE fft_base,        ONLY : dffts, dfftp
    USE fft_interfaces,  ONLY : fwfft, invfft
    USE klist,           ONLY : nkstot, xk, igk_k, ngk
@@ -1905,7 +1905,7 @@
    USE kinds,           ONLY: DP
    USE wvfct,           ONLY : nbnd, npwx
    USE control_flags,   ONLY : gamma_only
-   USE wavefunctions_module, ONLY : evc, psic, psic_nc
+   USE wavefunctions, ONLY : evc, psic, psic_nc
    USE fft_base,        ONLY : dffts, dfftp
    USE fft_interfaces,  ONLY : fwfft, invfft
    USE klist,           ONLY : nkstot, xk, igk_k, ngk
@@ -2300,7 +2300,7 @@
    USE kinds,           ONLY: DP
    USE wvfct,           ONLY : nbnd, npwx
    USE control_flags,   ONLY : gamma_only
-   USE wavefunctions_module, ONLY : evc, psic, psic_nc
+   USE wavefunctions, ONLY : evc, psic, psic_nc
    USE fft_base,        ONLY : dffts, dfftp
    USE fft_interfaces,  ONLY : fwfft, invfft
    USE klist,           ONLY : nkstot, xk, ngk, igk_k
@@ -2542,7 +2542,7 @@
    USE kinds,           ONLY: DP
    USE wvfct,           ONLY : nbnd, npwx, current_k
    USE control_flags,   ONLY : gamma_only
-   USE wavefunctions_module, ONLY : evc, psic, psic_nc
+   USE wavefunctions, ONLY : evc, psic, psic_nc
    USE fft_base,        ONLY : dffts, dfftp
    USE fft_interfaces,  ONLY : fwfft, invfft
    USE klist,           ONLY : nkstot, xk, ngk, igk_k
@@ -2964,7 +2964,7 @@
    USE klist,           ONLY : nkstot, xk, ngk, igk_k
    USE wvfct,           ONLY : nbnd, npwx
    USE control_flags,   ONLY : gamma_only
-   USE wavefunctions_module, ONLY : evc
+   USE wavefunctions, ONLY : evc
    USE io_files,        ONLY : nwordwfc, iunwfc
    USE gvect,           ONLY : g, ngm, gstart
    USE uspp,            ONLY : nkb, vkb
@@ -3237,7 +3237,7 @@
    USE wvfct,           ONLY : nbnd, et
    USE gvecw,           ONLY : gcutw
    USE control_flags,   ONLY : gamma_only
-   USE wavefunctions_module, ONLY : evc, psic
+   USE wavefunctions, ONLY : evc, psic
    USE io_files,        ONLY : nwordwfc, iunwfc
    USE wannier
    USE klist,           ONLY : nkstot, xk, ngk, igk_k
@@ -3754,7 +3754,7 @@
    USE wvfct, ONLY : nbnd, npwx
    USE gvecw, ONLY : gcutw
    USE control_flags, ONLY : gamma_only
-   USE wavefunctions_module, ONLY : evc, psic, psic_nc
+   USE wavefunctions, ONLY : evc, psic, psic_nc
    USE io_files, ONLY : nwordwfc, iunwfc
    USE wannier
    USE klist,           ONLY : nkstot, xk, ngk, igk_k
@@ -4021,7 +4021,7 @@
    USE wvfct,                ONLY : nbnd
    USE gvecw,                ONLY : gcutw
    USE control_flags,        ONLY : gamma_only
-   USE wavefunctions_module, ONLY : evc
+   USE wavefunctions, ONLY : evc
    USE io_files,             ONLY : nwordwfc, iunwfc
    USE wannier
    USE klist,                ONLY : nkstot, xk, igk_k, ngk
@@ -4428,7 +4428,7 @@
   USE kinds, ONLY : DP
   USE io_files, ONLY : iunwfc, nwordwfc, nwordwann
   USE gvect, ONLY : g, ngm
-  USE wavefunctions_module, ONLY : evc, psic
+  USE wavefunctions, ONLY : evc, psic
   USE wvfct, ONLY : nbnd, npwx
   USE gvecw, ONLY : gcutw
   USE klist, ONLY : nkstot, xk, wk, ngk
```

- Between the 6.3 version in QE and the 6.3 version in Wannier90, there have been a few bug fixes:
```diff
--- pw2wannier90-qe-6.3.f90.txt	2019-01-23 07:38:53.000000000 +0100
+++ pw2wannier90-w90-post621.f90.txt	2019-01-23 07:40:03.000000000 +0100
@@ -82,6 +82,7 @@
    real(DP), allocatable    :: eigval(:,:)
    logical                  :: old_spinor_proj  ! for compatability for nnkp files prior to W90v2.0
    integer,allocatable :: rir(:,:)
+   logical,allocatable :: zerophase(:,:)
 end module wannier
 !
 
@@ -604,9 +605,14 @@
   nnb=max(nnbx,nnb)
 
   ALLOCATE( ig_(iknum,nnb), ig_check(iknum,nnb) )
+  ALLOCATE( zerophase(iknum,nnb) )
+  zerophase = .false.
 
   DO ik=1, iknum
      DO ib = 1, nnb
+        IF ( (g_kpb(1,ik,ib).eq.0) .and.  &
+             (g_kpb(2,ik,ib).eq.0) .and.  &
+             (g_kpb(3,ik,ib).eq.0) ) zerophase(ik,ib) = .true.
         g_(:) = REAL( g_kpb(:,ik,ib) )
         CALL cryst_to_cart (1, g_, bg, 1)
         gg_ = g_(1)*g_(1) + g_(2)*g_(2) + g_(3)*g_(3)
@@ -1022,6 +1028,8 @@
   !
   ALLOCATE ( kpb(iknum,nnbx), g_kpb(3,iknum,nnbx),&
              ig_(iknum,nnbx), ig_check(iknum,nnbx) )
+  ALLOCATE( zerophase(iknum,nnbx) )
+  zerophase = .false.
 
   !  read data about neighbours
   WRITE(stdout,*)
@@ -1042,6 +1050,9 @@
 
   DO ik=1, iknum
      DO ib = 1, nnb
+        IF ( (g_kpb(1,ik,ib).eq.0) .and.  &
+             (g_kpb(2,ik,ib).eq.0) .and.  &
+             (g_kpb(3,ik,ib).eq.0) ) zerophase(ik,ib) = .true.
         g_(:) = REAL( g_kpb(:,ik,ib) )
         CALL cryst_to_cart (1, g_, bg, 1)
         gg_ = g_(1)*g_(1) + g_(2)*g_(2) + g_(3)*g_(3)
@@ -1938,7 +1949,7 @@
                                becp2(:,:), Mkb(:,:), aux_nc(:,:), becp2_nc(:,:,:)
    real(DP), ALLOCATABLE    :: rbecp2(:,:)
    COMPLEX(DP), ALLOCATABLE :: qb(:,:,:,:), qgm(:), qq_so(:,:,:,:)
-   real(DP), ALLOCATABLE    :: qg(:), ylm(:,:), dxk(:,:), workg(:)
+   real(DP), ALLOCATABLE    :: qg(:), ylm(:,:), dxk(:,:)
    COMPLEX(DP)              :: mmn, zdotc, phase1
    real(DP)                 :: arg, g_(3)
    CHARACTER (len=9)        :: cdate,ctime
@@ -1992,32 +2003,27 @@
       ELSE
          ALLOCATE ( becp2(nkb,nbnd) )
       ENDIF
-   ENDIF
-   !
-   !     qb is  FT of Q(r)
-   !
-   nbt = nnb * iknum
-   !
-   ALLOCATE( qg(nbt) )
-   ALLOCATE (dxk(3,nbt))
-   !
-   ind = 0
-   DO ik=1,iknum
-      DO ib=1,nnb
-         ind = ind + 1
-         ikp = kpb(ik,ib)
-         !
-         g_(:) = REAL( g_kpb(:,ik,ib) )
-         CALL cryst_to_cart (1, g_, bg, 1)
-         dxk(:,ind) = xk(:,ikp) +g_(:) - xk(:,ik)
-         qg(ind) = dxk(1,ind)*dxk(1,ind)+dxk(2,ind)*dxk(2,ind)+dxk(3,ind)*dxk(3,ind)
+      !
+      !     qb is  FT of Q(r)
+      !
+      nbt = nnb * iknum
+      !
+      ALLOCATE( qg(nbt) )
+      ALLOCATE (dxk(3,nbt))
+      !
+      ind = 0
+      DO ik=1,iknum
+         DO ib=1,nnb
+            ind = ind + 1
+            ikp = kpb(ik,ib)
+            !
+            g_(:) = REAL( g_kpb(:,ik,ib) )
+            CALL cryst_to_cart (1, g_, bg, 1)
+            dxk(:,ind) = xk(:,ikp) +g_(:) - xk(:,ik)
+            qg(ind) = dxk(1,ind)*dxk(1,ind)+dxk(2,ind)*dxk(2,ind)+dxk(3,ind)*dxk(3,ind)
+         ENDDO
+!         write (stdout,'(i3,12f8.4)')  ik, qg((ik-1)*nnb+1:ik*nnb)
       ENDDO
-!      write (stdout,'(i3,12f8.4)')  ik, qg((ik-1)*nnb+1:ik*nnb)
-   ENDDO
-   !
-   !  USPP
-   !
-   IF(any_uspp) THEN
 
       ALLOCATE( ylm(nbt,lmaxq*lmaxq), qgm(nbt) )
       ALLOCATE( qb (nhm, nhm, ntyp, nbt) )
@@ -2044,7 +2050,6 @@
    WRITE(stdout,'(a,i8)') '  MMN: iknum = ',iknum
    !
    ALLOCATE( Mkb(nbnd,nbnd) )
-   ALLOCATE( workg(npwx) )
    !
    ind = 0
    DO ik=1,iknum
@@ -2076,9 +2081,11 @@
             CALL davcio (evcq, 2*nwordwfc, iunwfc, ikpevcq, -1 )
 !         end if
 ! compute the phase
-         phase(:) = (0.d0,0.d0)
-         IF ( ig_(ik,ib)>0) phase( dffts%nl(ig_(ik,ib)) ) = (1.d0,0.d0)
-         CALL invfft ('Wave', phase, dffts)
+         IF (.not.zerophase(ik,ib)) THEN
+            phase(:) = (0.d0,0.d0)
+            IF ( ig_(ik,ib)>0) phase( dffts%nl(ig_(ik,ib)) ) = (1.d0,0.d0)
+            CALL invfft ('Wave', phase, dffts)
+         ENDIF
          !
          !  USPP
          !
@@ -2184,19 +2191,23 @@
                   istart=(ipol-1)*npwx+1
                   iend=istart+npw-1
                   psic_nc(dffts%nl (igk_k(1:npw,ik) ),ipol ) = evc(istart:iend, m)
-                  CALL invfft ('Wave', psic_nc(:,ipol), dffts)
-                  psic_nc(1:dffts%nnr,ipol) = psic_nc(1:dffts%nnr,ipol) * &
+		  IF (.not.zerophase(ik,ib)) THEN
+                     CALL invfft ('Wave', psic_nc(:,ipol), dffts)
+                     psic_nc(1:dffts%nnr,ipol) = psic_nc(1:dffts%nnr,ipol) * &
                                                  phase(1:dffts%nnr)
-                  CALL fwfft ('Wave', psic_nc(:,ipol), dffts)
+                     CALL fwfft ('Wave', psic_nc(:,ipol), dffts)
+                  ENDIF
                   aux_nc(1:npwq,ipol) = psic_nc(dffts%nl (igk_k(1:npwq,ikp)),ipol )
                ENDDO
             ELSE
                psic(:) = (0.d0, 0.d0)
                psic(dffts%nl (igk_k (1:npw,ik) ) ) = evc (1:npw, m)
                IF(gamma_only) psic(dffts%nlm(igk_k(1:npw,ik) ) ) = conjg(evc (1:npw, m))
-               CALL invfft ('Wave', psic, dffts)
-               psic(1:dffts%nnr) = psic(1:dffts%nnr) * phase(1:dffts%nnr)
-               CALL fwfft ('Wave', psic, dffts)
+               IF (.not.zerophase(ik,ib)) THEN
+                  CALL invfft ('Wave', psic, dffts)
+                  psic(1:dffts%nnr) = psic(1:dffts%nnr) * phase(1:dffts%nnr)
+                  CALL fwfft ('Wave', psic, dffts)
+               ENDIF
                aux(1:npwq)  = psic(dffts%nl (igk_k(1:npwq,ikp) ) )
             ENDIF
             IF(gamma_only) THEN
@@ -2258,12 +2269,12 @@
 
       ENDDO !ib
    ENDDO  !ik
-   DEALLOCATE(workg)
    
    IF (ionode .and. wan_mode=='standalone') CLOSE (iun_mmn)
 
    IF (gamma_only) DEALLOCATE(aux2)
-   DEALLOCATE (Mkb, dxk, phase)
+   DEALLOCATE (Mkb, phase)
+   IF (any_uspp) DEALLOCATE (dxk)
    IF(noncolin) THEN
       DEALLOCATE(aux_nc)
    ELSE
```
